services:
  mysql:
    container_name: 'kelprint-gerenciamento-de-pedidos'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=kelprint-db'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'