version: '3.8'
services:
  db:
    container_name: 'kelprint-gerenciamento-de-pedidos'
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=kelprint-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'